{
	"name": "CVE-2024-53908",
	"description": "An issue was discovered in Django 5.1 before 5.1.4, 5.0 before 5.0.10, and 4.2 before 4.2.17. Direct usage of the django.db.models.fields.json.HasKey lookup, when an Oracle database is used, is subject to SQL injection if untrusted data is used as an lhs value. (Applications that use the jsonfield.has_key lookup via __ are unaffected.)",
	"type": "none",
	"severity": "none",
	"state": "published",
	"references": [
		"https://docs.djangoproject.com/en/dev/releases/security/",
		"https://groups.google.com/g/django-announce",
		"https://www.openwall.com/lists/oss-security/2024/12/04/3"
	],
	"datetime": "2025-02-06 12:35:25",
	"connections": [],
	"devices": [],
	"distributions": [
		{
			"name": "debian",
			"version": "bookworm",
			"vendor": "debian-bookworm"
		},
		{
			"name": "debian",
			"version": "sid",
			"vendor": "debian-sid"
		},
		{
			"name": "debian",
			"version": "trixie",
			"vendor": "debian-trixie"
		},
		{
			"name": "debian",
			"version": "bullseye",
			"vendor": "debian-bullseye"
		}
	],
	"packages": [
		{
			"name": "python-django",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-bookworm"
		},
		{
			"name": "python-django",
			"version": "\u003c 3:4.2.17-1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-sid"
		},
		{
			"name": "python-django",
			"version": "\u003c 2:2.2.28-1~deb11u2",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-bullseye"
		}
	],
	"products": [],
	"programs": [],
	"weaknesses": [
		{
			"name": "CWE-89",
			"impact": "any",
			"scope": "any"
		}
	]
}