{
	"name": "CVE-2024-56374",
	"description": "An issue was discovered in Django 5.1 before 5.1.5, 5.0 before 5.0.11, and 4.2 before 4.2.18. Lack of upper-bound limit enforcement in strings passed when performing IPv6 validation could lead to a potential denial-of-service attack. The undocumented and private functions clean_ipv6_address and is_valid_ipv6_address are vulnerable, as is the django.forms.GenericIPAddressField form field. (The django.db.models.GenericIPAddressField model field is not affected.)",
	"type": "none",
	"severity": "none",
	"state": "published",
	"references": [
		"https://docs.djangoproject.com/en/dev/releases/security/",
		"https://groups.google.com/g/django-announce",
		"https://www.djangoproject.com/weblog/2025/jan/14/security-releases/",
		"http://www.openwall.com/lists/oss-security/2025/01/14/2",
		"https://lists.debian.org/debian-lts-announce/2025/01/msg00024.html"
	],
	"datetime": "2025-02-06 12:35:28",
	"connections": [],
	"devices": [],
	"distributions": [
		{
			"name": "debian",
			"version": "bookworm",
			"vendor": "debian-bookworm"
		},
		{
			"name": "debian",
			"version": "bullseye",
			"vendor": "debian-bullseye"
		},
		{
			"name": "debian",
			"version": "sid",
			"vendor": "debian-sid"
		},
		{
			"name": "debian",
			"version": "trixie",
			"vendor": "debian-trixie"
		}
	],
	"packages": [
		{
			"name": "python-django",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-bookworm"
		},
		{
			"name": "python-django",
			"version": "\u003c 2:2.2.28-1~deb11u5",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-bullseye"
		},
		{
			"name": "python-django",
			"version": "\u003c 3:4.2.18-1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "debian-sid"
		}
	],
	"products": [],
	"programs": [],
	"weaknesses": [
		{
			"name": "CWE-770",
			"impact": "any",
			"scope": "any"
		}
	]
}